// docs/src/components/app-sidebar.tsx
"use client";

import { NavMenu, type NavMenuGroup } from "@/components/nav-menu";
import { NavSourceCode } from "@/components/nav-source-code";
import { SidebarLogo } from "@/components/sidebar-logo";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader } from "@/components/ui/sidebar";
import * as React from "react";
import { GrMapLocation } from "react-icons/gr";
import { MdOutlineTouchApp } from "react-icons/md";
import { SlBookOpen } from "react-icons/sl";

const navMenus: NavMenuGroup[] = [
  {
    title: "Getting Started",
    url: "#",
    icon: MdOutlineTouchApp,
    isActive: true,
    items: [
      { title: "Overview", url: "/" },
      { title: "Tentang API", url: "/tentang-api" },
      { title: "Fitur Utama", url: "/fitur-utama" },
      { title: "Panduan Instalasi", url: "/paduan-instalasi" },
    ],
  },
  {
    title: "API Documentation",
    url: "#",
    icon: SlBookOpen,
    isActive: true,
    items: [
      { title: "GET Provinsi", url: "/api-documentation/get-provinsi" },
      { title: "GET Kabupaten/Kota", url: "/api-documentation/get-kabupaten-kota" },
      { title: "GET Kecamatan", url: "/api-documentation/get-kecamatan" },
      { title: "GET Desa/Kelurahan", url: "/api-documentation/get-desa-kelurahan" },
    ],
  },
  {
    title: "Data Wilayah",
    url: "#",
    icon: GrMapLocation,
    isActive: true,
    items: [
      { title: "Provinsi", url: "/data-wilayah/provinsi" },
      { title: "Kabupaten/Kota", url: "/data-wilayah/kabupaten-kota" },
      { title: "Kecamatan", url: "/data-wilayah/kecamatan" },
      { title: "Desa/Kelurahan", url: "/data-wilayah/desa-kelurahan" },
    ],
  },
];

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  return (
    <Sidebar collapsible="icon" {...props}>
      <SidebarHeader>
        <SidebarLogo />
      </SidebarHeader>
      <SidebarContent>
        <NavMenu items={navMenus} />
      </SidebarContent>
      <SidebarFooter>
        <NavSourceCode />
      </SidebarFooter>
    </Sidebar>
  );
}

// docs/src/components/AppSidebar.vue
<script setup lang="ts">
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  type SidebarProps,
  SidebarRail,
} from '@/components/ui/sidebar'

const props = defineProps<SidebarProps>()

const data = {
  navMain: [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        {
          title: 'Overview',
          url: '/',
          isActive: false,
        },
        {
          title: 'Tentang API',
          url: '/tentang-api',
          isActive: false,
        },
        {
          title: 'Fitur Utama',
          url: '/fitur-utama',
          isActive: false,
        },
        {
          title: 'Panduan Instalasi',
          url: '/panduan-instalasi',
          isActive: false,
        },
      ],
    },
    {
      title: 'API Documentation',
      url: '#',
      items: [
        {
          title: 'GET Provinsi',
          url: '/api-documentation/get-provinsi',
          isActive: false,
        },
        {
          title: 'GET Kabupaten/Kota',
          url: '/api-documentation/get-kabupaten-kota',
          isActive: false,
        },
        {
          title: 'GET Kecamatan',
          url: '/api-documentation/get-kecamatan',
          isActive: false,
        },
        {
          title: 'GET Desa/Kelurahan',
          url: '/api-documentation/get-desa-kelurahan',
          isActive: false,
        },
      ],
    },
    {
      title: 'Data Wilayah',
      url: '#',
      items: [
        {
          title: 'Provinsi',
          url: '/data-wilayah/provinsi',
          isActive: false,
        },
        {
          title: 'Kabupaten/Kota',
          url: '/data-wilayah/kabupaten-kota',
          isActive: false,
        },
        {
          title: 'Kecamatan',
          url: '/data-wilayah/kecamatan',
          isActive: false,
        },
        {
          title: 'Desa/Kelurahan',
          url: '/data-wilayah/desa-kelurahan',
          isActive: false,
        },
      ],
    },
  ],
}
</script>

<template>
  <Sidebar v-bind="props">
    <SidebarHeader>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton size="lg" as-child>
            <a href="/">
              <div class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                <img src="/logo.png" alt="logo nusantara kita">
              </div>
              <div class="flex flex-col gap-0.5 leading-none">
                <span class="font-medium">Nusantara Kita</span>
                <span class="">v2.0</span>
              </div>
            </a>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarHeader>
    <SidebarContent>
      <SidebarGroup>
        <SidebarMenu>
          <SidebarMenuItem v-for="item in data.navMain" :key="item.title">
            <SidebarMenuButton as-child>
              <a :href="item.url" class="font-medium">
                {{ item.title }}
              </a>
            </SidebarMenuButton>
            <SidebarMenuSub v-if="item.items.length">
              <SidebarMenuSubItem v-for="childItem in item.items" :key="childItem.title">
                <SidebarMenuSubButton as-child :is-active="childItem.isActive">
                  <a :href="childItem.url">{{ childItem.title }}</a>
                </SidebarMenuSubButton>
              </SidebarMenuSubItem>
            </SidebarMenuSub>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarGroup>
    </SidebarContent>
    <SidebarRail />
  </Sidebar>
</template>
